- name: ensure the nginx working directory
  tags:
    - nginx-install
    - nginx-config
  command: mkdir -p {{ nginx_working_dir }}
  notify:
    - cleanup the nginx working directory

- name: ensure directories
  tags:
    - nginx-install
    - nginx-config
  file: path={{ item }} owner={{ nginx_user }} group={{ nginx_group }}
    mode=0755 recurse=yes state=directory
  with_items:
    - '{{ nginx_home_dir }}'
    - '{{ nginx_home_dir }}/run'
    - '{{ nginx_log_dir }}'

- include: install.yaml
- include: upstart.yaml
- include: config.yaml
